Add back non-push version of function XrdAccAuthorizeObject
xrootd/xrootd-scitokens pull request #6
Opened 2020-11-24 16:16 UTC by djw8605

Want to make sure backwards compatibility continues.

2020-11-25 00:08 UTC, abh3 requested changes
Pretty much what has to be done. So, looks just fine. I am requesting one change that has nothing to do with your changes. It's removal of an unused extern.

2020-11-25 00:08 UTC, abh3 commented on src/XrdAccSciTokens.cc
>  extern XrdAccAuthorize *XrdAccDefaultAuthorizeObject(XrdSysLogger   *lp,
Could you get rid of this extern as it's not used anywhere (it's a holdover) and we eventually want to get rid of it.

2020-11-25 00:09 UTC, abh3 commented
Done. See comment.

On Tue, 24 Nov 2020, Derek Weitzel wrote:

> @djw8605 requested your review on: xrootd/xrootd-scitokens#6 Add back non-push version of function XrdAccAuthorizeObject.
>
> -- 
> You are receiving this because your review was requested.
> Reply to this email directly or view it on GitHub:
> https://github.com/xrootd/xrootd-scitokens/pull/6#event-4033675150

2020-11-30 21:57 UTC, djw8605 commented
Removed extern.

2020-11-30 23:25 UTC, merged